// Lista única de categorias de vaga.
// Usada tanto no filtro do mapa (app/mapa/page.tsx) quanto no formulário
// de publicar vaga (app/publicar-vaga/page.tsx), para garantir que o texto
// salvo no campo `area` sempre bate com as opções do filtro.

export const CATEGORIAS_VAGA = [
  "Entregador",
  "Motoboy",
  "Estoquista",
  "Repositor de Mercadorias",
  "Auxiliar de Depósito",
  "Auxiliar de Almoxarifado",
  "Ajudante Geral",
  "Servente",
  "Carregador",
  "Descarregador",
  "Empacotador",
  "Separador de Mercadorias",
  "Operador de Caixa",
  "Atendente",
  "Balconista",
  "Vendedor",
  "Promotor de Vendas",
  "Panfleteiro",
  "Recepcionista",
  "Porteiro",
  "Vigia",
  "Frentista",
  "Lavador de Veículos",
  "Borracheiro",
  "Auxiliar de Limpeza",
  "Faxineiro",
  "Zelador",
  "Jardineiro",
  "Garçom",
  "Auxiliar de Cozinha",
  "Chapeiro",
  "Pizzaiolo",
  "Confeiteiro",
  "Cozinheiro",
  "Ajudante de Pedreiro",
  "Pedreiro",
  "Pintor",
  "Eletricista",
  "Encanador",
  "Marceneiro",
  "Soldador",
  "Mecânico",
  "Costureira",
  "Babá",
  "Cuidador de Idosos",
  "Diarista",
  "Doméstica",
  "Cabeleireiro",
  "Barbeiro",
  "Manicure",
] as const;